services:
  - type: web
    name: elite-track-vms
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false # You will provide this in the Render dashboard
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 30d
      - key: VITE_API_URL
        value: /api
      - key: PORT
        value: 5000
